spring.application.name=loan-application


# =========================
# DATABASE
# =========================


spring.datasource.url=jdbc:mysql://localhost:3306/BidSystem
spring.datasource.username=USERNAME
spring.datasource.password=root

# Hibernate will automatically create/update tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true







app.jwt.secret=${JWT_SECRET:change-this-development-secret-key-please-123456789}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:900000}




spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=abhishekkokitkar35@gmail.com
spring.mail.password=nqdv ecsd ftoc hnyo

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true